FROM ubuntu:xenial

MAINTAINER trevorcarl@gmail.com
#MAINTAINER ping@mirceaulinic.net

## Install min deps
RUN apt-get update \
    && apt-get install -y apt-transport-https \
    && apt-get install -y ca-certificates \
    && apt-get install -y wget \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

## Setup sources for SaltStack repo
RUN echo 'deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2 xenial main' > /etc/apt/sources.list.d/saltstack.list \
    && wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub  | apt-key add - \
    && apt-get update

## Install the Salt Master
RUN apt-get install -y salt-master salt-minion salt-ssh salt-syndic salt-api salt-cloud

ADD master /etc/salt/master

# Add Run File
ADD run-master.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

# Ports
EXPOSE 4505 4506

# Run Command
CMD "/usr/local/bin/run.sh"
